name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install APKTool
        run: |
          sudo apt-get install -y wget tar openjdk-11-jdk
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.6.0/apktool_2.6.0.jar -O apktool.jar
          echo '#!/bin/bash\njava -jar /usr/local/bin/apktool.jar "$@"' > apktool
          chmod +x apktool
          sudo mv apktool /usr/local/bin/
          sudo mv apktool.jar /usr/local/bin/

      - name: Convert JAR to APK
        run: |
          apktool d .github/workflows/Hesapmakinesi.jar -o .github/workflows/apk
       
          
          
          
          
      - name: Upload APK file
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: .github/workflows/apk

      - name: Download APK file
        uses: actions/download-artifact@v2
        with:
          name: apk

      - name: Build APK
        run: |
          # Use apktool or other tools to build the APK
          echo "APK file created"
